### ISSUE TITLE
Suggestion - Add a guide explaining how to contribute to epitaph

### ISSUE THREAD

**Issue by matty45** [HaloBible/wiki#21]
Ditto

**Comment by no1dead** [comment]
Once I have the free time to do it I will be adding a contributing page to the wiki.

**Comment by MegaMech** [comment]
I can do it to if you don't have time. (Or start it)

**Comment by MegaMech** [comment]
Please close this issue
PR#25 adds the requested information.

**Comment by no1dead** [comment]
Closed.
