### ISSUE TITLE
Somehow get rid of the weird duplicated folders.

### ISSUE THREAD

**Issue by matty45** [HaloBible/wiki#32]
it would be nice if we somehow had:

> https://epitaph.dev/docs/Tools/MegHalomaniac

instead of 

> https://epitaph.dev/docs/Tools/MegHalomaniac/MegHalomaniac/

Im not sure what is causing this but i think it could be a Jekyll thing.

**Comment by MegaMech** [comment]
This happens because:
Folder name > Article name
Example:
Assembly > Assembly.md
Result:
Assembly/Assembly

It may be possible to add index.md in the folders which could have the same functional outcome but would look like:
Assembly > index.md
Result
/Assembly

**Comment by no1dead** [comment]
i'll test this out real quick

**Comment by no1dead** [comment]
tested and it works. I'll see about removing the /docs and it should be a lot cleaner.

**Comment by MegaMech** [comment]
This can probably be closed after PR 39 is accepted. It's likely you cannot remove /docs/ without modifying Just the Docs.

**Comment by PaleLebouf** [comment]
Resolved
